# Generated by Django 4.0.4 on 2022-09-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_topic_listing_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='topic',
            new_name='category',
        ),
    ]
