# Generated by Django 4.0.4 on 2022-09-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_listing_watchlist_watchlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='updated',
        ),
    ]
